--------------------------------------------------------
--  파일이 생성됨 - 화요일-8월-08-2023   
--------------------------------------------------------
DROP TABLE "GAONNURIWEB"."USER_TBL" cascade constraints;
--------------------------------------------------------
--  DDL for Table USER_TBL
--------------------------------------------------------

  CREATE TABLE "GAONNURIWEB"."USER_TBL" 
   (	"USER_ID" VARCHAR2(20 BYTE), 
	"USER_PW" VARCHAR2(12 BYTE), 
	"USER_NAME" VARCHAR2(30 BYTE), 
	"USER_PHONE" VARCHAR2(11 BYTE), 
	"USER_EMAIL" VARCHAR2(50 BYTE), 
	"USER_EVENT_YN" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into GAONNURIWEB.USER_TBL
SET DEFINE OFF;
Insert into GAONNURIWEB.USER_TBL (USER_ID,USER_PW,USER_NAME,USER_PHONE,USER_EMAIL,USER_EVENT_YN) values ('user01','pass01','일용자','01001010101','user01@test.com','N');
Insert into GAONNURIWEB.USER_TBL (USER_ID,USER_PW,USER_NAME,USER_PHONE,USER_EMAIL,USER_EVENT_YN) values ('user02','pass02','이용자','01022222222','user02@test.com','Y');
Insert into GAONNURIWEB.USER_TBL (USER_ID,USER_PW,USER_NAME,USER_PHONE,USER_EMAIL,USER_EVENT_YN) values ('user03','pass03','삼용자','01033333333',null,'Y');
Insert into GAONNURIWEB.USER_TBL (USER_ID,USER_PW,USER_NAME,USER_PHONE,USER_EMAIL,USER_EVENT_YN) values ('user04','pass04','사용자','01044444444','user04@test.com','N');
--------------------------------------------------------
--  DDL for Index SYS_C007307
--------------------------------------------------------

  CREATE UNIQUE INDEX "GAONNURIWEB"."SYS_C007307" ON "GAONNURIWEB"."USER_TBL" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007308
--------------------------------------------------------

  CREATE UNIQUE INDEX "GAONNURIWEB"."SYS_C007308" ON "GAONNURIWEB"."USER_TBL" ("USER_PHONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table USER_TBL
--------------------------------------------------------

  ALTER TABLE "GAONNURIWEB"."USER_TBL" ADD UNIQUE ("USER_PHONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GAONNURIWEB"."USER_TBL" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GAONNURIWEB"."USER_TBL" MODIFY ("USER_PHONE" NOT NULL ENABLE);
  ALTER TABLE "GAONNURIWEB"."USER_TBL" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "GAONNURIWEB"."USER_TBL" MODIFY ("USER_PW" NOT NULL ENABLE);

COMMIT;