--------------------------------------------------------
--  파일이 생성됨 - 화요일-8월-08-2023   
--------------------------------------------------------
DROP TABLE "GAONNURIWEB"."RESERVE_TBL" cascade constraints;
--------------------------------------------------------
--  DDL for Table RESERVE_TBL
--------------------------------------------------------

  CREATE TABLE "GAONNURIWEB"."RESERVE_TBL" 
   (	"RESERVE_PLACE" VARCHAR2(10 BYTE), 
	"RESERVE_DATE" DATE, 
	"RESERVE_TIME" VARCHAR2(7 BYTE), 
	"RESERVE_PEOPLE" NUMBER, 
	"RESERVE_NAME" VARCHAR2(30 BYTE), 
	"RESERVE_PHONE" VARCHAR2(11 BYTE), 
	"RESERVE_EMAIL" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into GAONNURIWEB.RESERVE_TBL
SET DEFINE OFF;
Insert into GAONNURIWEB.RESERVE_TBL (RESERVE_PLACE,RESERVE_DATE,RESERVE_TIME,RESERVE_PEOPLE,RESERVE_NAME,RESERVE_PHONE,RESERVE_EMAIL) values ('덕수궁',to_date('23/08/24','RR/MM/DD'),'18 : 40',2,'이용자','01022222222',null);
Insert into GAONNURIWEB.RESERVE_TBL (RESERVE_PLACE,RESERVE_DATE,RESERVE_TIME,RESERVE_PEOPLE,RESERVE_NAME,RESERVE_PHONE,RESERVE_EMAIL) values ('창덕궁',to_date('23/08/28','RR/MM/DD'),'19 : 40',5,'예매자','01012364567','user@test.com');
Insert into GAONNURIWEB.RESERVE_TBL (RESERVE_PLACE,RESERVE_DATE,RESERVE_TIME,RESERVE_PEOPLE,RESERVE_NAME,RESERVE_PHONE,RESERVE_EMAIL) values ('덕수궁',to_date('23/08/21','RR/MM/DD'),'19 : 40',5,'일용자','01011111111','user01@test.com');
Insert into GAONNURIWEB.RESERVE_TBL (RESERVE_PLACE,RESERVE_DATE,RESERVE_TIME,RESERVE_PEOPLE,RESERVE_NAME,RESERVE_PHONE,RESERVE_EMAIL) values ('창경궁',to_date('23/08/21','RR/MM/DD'),'19 : 40',2,'사용자','01044444444','user04@test.com');
--------------------------------------------------------
--  Constraints for Table RESERVE_TBL
--------------------------------------------------------

  ALTER TABLE "GAONNURIWEB"."RESERVE_TBL" MODIFY ("RESERVE_PHONE" NOT NULL ENABLE);
  ALTER TABLE "GAONNURIWEB"."RESERVE_TBL" MODIFY ("RESERVE_NAME" NOT NULL ENABLE);
  ALTER TABLE "GAONNURIWEB"."RESERVE_TBL" MODIFY ("RESERVE_PEOPLE" NOT NULL ENABLE);
  ALTER TABLE "GAONNURIWEB"."RESERVE_TBL" MODIFY ("RESERVE_TIME" NOT NULL ENABLE);
  ALTER TABLE "GAONNURIWEB"."RESERVE_TBL" MODIFY ("RESERVE_DATE" NOT NULL ENABLE);
  ALTER TABLE "GAONNURIWEB"."RESERVE_TBL" MODIFY ("RESERVE_PLACE" NOT NULL ENABLE);

COMMIT;